### PR TITLE
compatible with sketch 64

### PR DESCRIPTION
**Pull request by zzzJH**
image

https://github.com/abynim/Sketch-Headers/commit/ce524852e5f1f948a52a4ed043a3c4b36fb2064a#diff-2e6721c2d801e437b6678cce78235955

### CODE REVIEW

**Review by mathieudutour — APPROVED** [review]
👍

**Comment by zzzJH** [comment]
> 👍

Can [@skpm/sketchapp-json-plugin](https://www.npmjs.com/package/@skpm/sketchapp-json-plugin) package release a new version for current pr ?

image

**Comment by mathieudutour** [comment]
I don't have the permissions. Ping @darknoon

**Comment by zzzJH** [comment]
> I don't have the permissions. Ping @darknoon

I'm confused. According to the NPMJS display, you should have permission.

image

**Comment by mathieudutour** [comment]
Ah sorry that's not the same package, it was my fork which I don't use anywhere anymore. Not sure I ever put it on GH

**Comment by zzzJH** [comment]
> Ah sorry that's not the same package, it was my fork which I don't use anywhere anymore. Not sure I ever put it on GH

i see. i will publish my own package, thx.

**Comment by matzimowski** [comment]
hello, @darknoon
are you planning to publish the latest version to npm?

**Pull request merged**
